import java.util.Random;

public enum Author {
	ERNEST_HEMINGWAY, WILLIAM_SHAKESPEARE, MARK_TWAIN, JK_ROWLING, CHARLES_DICKENS, STEPHEN_KING, JANE_AUSTEN, JAMES_JOYCE, F_SCOTT_FITZGERALD, AGATHA_CHRISTIE, JRR_TOLKIEN, VIRGINIA_WOOLF, LEV_TOLSTOJ, GEORGE_ORWELL, CS_LEWIS, FYODOR_DOSTOYEVSKI, OSCAR_WILDE, WILLIAM_FAULKNER, JOHN_STEINBECK, FRANZ_KAFKA, LEWIS_CARROLL, VLADIMIR_NABOKOV, JD_SALINGER, EDGAR_ALLAN_POE, ROALD_DAHL, NEIL_GAIMAN, KURT_VONNEGUT, JOSEPH_HELLER;
	 
	private static final Random rand = new Random();

	public static Author getRandomAuthor() {
		return Author.values()[rand.nextInt(Author.values().length)];
	}
}
